### ISSUE TITLE
Use getopt to enable advanced usage

### ISSUE THREAD

**Issue by pschord** [psforever/PSPack#5]
Options to consider
- -c, --create (pack)
- -x, --extract (unpack)
- -v, --verbose (verbose level increase)
- -d, --debug (debug level increase)

`./pspack.exe [options] -[cx] [action args]`

Pack example: `./pspack -c packtocreate.pak file1..filen`
Unpack with verbose: `./pspack -vx packtoextract.pak`

**Comment by psmook** [comment]
At this point my version differs far too much (I think) for a simple pull request. So here's my run at this issue:

https://github.com/psmook/PSPack-Win/blob/master/pspack.c#L68

**Comment by pschord** [comment]
Started in #10
